# Generated by Django 6.0 on 2026-01-02 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Firma Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Yetkili Kişi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=100, verbose_name='Yükleme Noktası')),
                ('destination', models.CharField(max_length=100, verbose_name='Teslimat Noktası')),
                ('status', models.CharField(choices=[('PENDING', 'Sipariş Alındı'), ('DISPATCHED', 'Araç Atandı / Yola Çıktı'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], default='PENDING', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taşıma Ücreti (TL)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.customer', verbose_name='Müşteri')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='fleet.driver', verbose_name='Sürücü')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='fleet.vehicle', verbose_name='Atanan Araç')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
