# Generated by Django 6.0 on 2026-01-08 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_driver_options_alter_vehicle_options_and_more'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sevkiyat', 'verbose_name_plural': 'Sevkiyatlar'},
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('VIP', 'VIP Müşteri'), ('STANDARD', 'Standart'), ('NEW', 'Yeni Müşteri')], default='STANDARD', max_length=20, verbose_name='Müşteri Tipi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Ciro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_shipments',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Sevkiyat'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Portal Hesabı'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Teslimat'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Yük Açıklaması'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Teslimat Notları'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_photo',
            field=models.URLField(blank=True, null=True, verbose_name='Teslimat Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Teslimat Enlem'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Teslimat Boylam'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim (TL)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mesafe (KM)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Teslimat'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_duration_mins',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tahmini Süre (dk)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ek Ücretler (TL)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Yükleme Enlem'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Yükleme Boylam'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='package_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Paket Sayısı'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Düşük'), ('NORMAL', 'Normal'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='NORMAL', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teslim Alan'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_signature',
            field=models.TextField(blank=True, null=True, verbose_name='İmza (Base64)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Referans No'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_token',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='Takip Kodu'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hacim (m³)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ağırlık (KG)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Sipariş Alındı'), ('CONFIRMED', 'Onaylandı'), ('DISPATCHED', 'Araç Atandı / Yola Çıktı'), ('IN_TRANSIT', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Fatura No')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SENT', 'Gönderildi'), ('PAID', 'Ödendi'), ('OVERDUE', 'Vadesi Geçmiş'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(verbose_name='Düzenleme Tarihi')),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ara Toplam')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KDV Tutarı')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İndirim')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Genel Toplam')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Nakit'), ('BANK_TRANSFER', 'Havale/EFT'), ('CREDIT_CARD', 'Kredi Kartı'), ('CHECK', 'Çek')], max_length=20, null=True, verbose_name='Ödeme Yöntemi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='logistics.customer')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.invoice')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Rota Adı')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=20)),
                ('start_location', models.CharField(max_length=200, verbose_name='Başlangıç Noktası')),
                ('start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Mesafe (KM)')),
                ('total_duration_mins', models.PositiveIntegerField(default=0, verbose_name='Toplam Süre (dk)')),
                ('total_stops', models.PositiveIntegerField(default=0, verbose_name='Durak Sayısı')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Planlanan Başlangıç')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Planlanan Bitiş')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Bitiş')),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='fleet.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Sipariş Alındı'), ('CONFIRMED', 'Onaylandı'), ('DISPATCHED', 'Araç Atandı / Yola Çıktı'), ('IN_TRANSIT', 'Yolda'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Durum Geçmişi',
                'verbose_name_plural': 'Durum Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(verbose_name='Sıra')),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Yükleme'), ('DELIVERY', 'Teslimat')], default='DELIVERY', max_length=20)),
                ('time_window_start', models.TimeField(blank=True, null=True, verbose_name='Pencere Başlangıç')),
                ('time_window_end', models.TimeField(blank=True, null=True, verbose_name='Pencere Bitiş')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('service_time_mins', models.PositiveIntegerField(default=15, verbose_name='Hizmet Süresi (dk)')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.route')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Rota Durağı',
                'verbose_name_plural': 'Rota Durakları',
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
    ]
