# Generated by Django 6.0 on 2026-01-08 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ayar Anahtarı')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_public', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturma'), ('UPDATE', 'Güncelleme'), ('DELETE', 'Silme'), ('LOGIN', 'Giriş'), ('LOGOUT', 'Çıkış'), ('EXPORT', 'Dışa Aktarma'), ('STATUS_CHANGE', 'Durum Değişikliği')], max_length=20)),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Adı')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nesne Açıklaması')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Değişiklikler')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('INFO', 'Bilgilendirme'), ('SUCCESS', 'Başarılı'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('SHIPMENT', 'Sevkiyat Bildirimi'), ('VEHICLE', 'Araç Bildirimi'), ('SYSTEM', 'Sistem Bildirimi')], default='INFO', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'Uygulama İçi'), ('EMAIL', 'E-posta'), ('SMS', 'SMS'), ('PUSH', 'Push Bildirim')], default='IN_APP', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('MANAGER', 'Filo Müdürü'), ('DISPATCHER', 'Sevkiyat Sorumlusu'), ('DRIVER', 'Sürücü'), ('CUSTOMER', 'Müşteri'), ('VIEWER', 'Salt Görüntüleyici')], default='VIEWER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Profil Fotoğrafı')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS Bildirimleri')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Bildirimleri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
