# Generated by Django 6.0 on 2026-01-02 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Ehliyet No')),
                ('is_available', models.BooleanField(default=True, verbose_name='Müsait mi?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Tır Çekici'), ('LORRY', 'Kamyon (Kırkayak)'), ('VAN', 'Panelvan'), ('PICKUP', 'Kamyonet')], default='TRUCK', max_length=10)),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model_year', models.PositiveIntegerField(verbose_name='Model Yılı')),
                ('capacity_kg', models.PositiveIntegerField(verbose_name='Yük Kapasitesi (KG)')),
                ('status', models.CharField(choices=[('IDLE', 'Garajda / Boş'), ('TRANSIT', 'Yolda / Seferde'), ('MAINTENANCE', 'Bakımda')], default='IDLE', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
