# Generated by Django 6.0 on 2026-01-08 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Sürücü', 'verbose_name_plural': 'Sürücüler'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Araç', 'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Ehliyet Bitiş'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Puan'),
        ),
        migrations.AddField(
            model_name='driver',
            name='successful_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='Başarılı Teslimat'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Teslimat'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Güncel KM'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Dizel'), ('GASOLINE', 'Benzin'), ('LPG', 'LPG'), ('ELECTRIC', 'Elektrik'), ('HYBRID', 'Hibrit')], default='DIESEL', max_length=20, verbose_name='Yakıt Tipi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Muayene Bitiş'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Sigorta Bitiş'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şasi No'),
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litre')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Litre Fiyatı (TL)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar (TL)')),
                ('odometer_reading', models.PositiveIntegerField(verbose_name='KM Sayacı')),
                ('fuel_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='İstasyon')),
                ('fill_date', models.DateTimeField(verbose_name='Alım Tarihi')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Yakıt Kaydı',
                'verbose_name_plural': 'Yakıt Kayıtları',
                'ordering': ['-fill_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('SCHEDULED', 'Planlı Bakım'), ('REPAIR', 'Arıza/Tamir'), ('INSPECTION', 'Muayene'), ('TIRE', 'Lastik Değişimi'), ('OIL', 'Yağ Değişimi'), ('BRAKE', 'Fren Bakımı'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Bakım Tipi')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planlandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi')], default='SCHEDULED', max_length=20)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('scheduled_date', models.DateField(verbose_name='Planlanan Tarih')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Sayacı')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maliyet (TL)')),
                ('service_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servis Sağlayıcı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Bakım Kaydı',
                'verbose_name_plural': 'Bakım Kayıtları',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Boylam')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rakım (m)')),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Hız (km/s)')),
                ('heading', models.PositiveIntegerField(default=0, verbose_name='Yön (derece)')),
                ('fuel_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yakıt Seviyesi (%)')),
                ('engine_on', models.BooleanField(default=False, verbose_name='Motor Açık')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adres')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Araç Konumu',
                'verbose_name_plural': 'Araç Konumları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='fleet_vehic_vehicle_704c3b_idx'), models.Index(fields=['-timestamp'], name='fleet_vehic_timesta_cab70f_idx')],
            },
        ),
    ]
